### ISSUE TITLE
Option to perform a user-specified number of repeats in parallel and average the results

### ISSUE THREAD

**Issue by xieaq** [yyolanda/SMART#1]
Hi Dr. @yyolanda 

I'm impressed by your work! 

But I do have a question regarding the stability part of the model.
 
‘To further improve the stability, SMART provides the option to perform a user-specified number of repeats in parallel and average the results.’ After checking the code, I couldn’t find any option to identify the more reliable results. Could you please give me any advice about that part?
 
I greatly appreciate your expertise and insights on these matters. Thank you in advance for your time and consideration.
 
Best regards!

**Comment by yyolanda** [comment]
Thank you @xieaq for your interest!

We used explicit code to run SMART in parallel and average the results because parallel computing may cause problems under different OS.  I have added the code to the main README page. Please feel free to let me know if you encounter any problems.

**Comment by xieaq** [comment]
> Thank you @xieaq for your interest!
> 
> We used explicit code to run SMART in parallel and average the results because parallel computing may cause problems under different OS. I have added the code to the main README page. Please feel free to let me know if you encounter any problems.

Thanks for your quick reply! Besides that, I'm wondering how to get the marker genes list. Do I need to define them manually?

**Comment by yyolanda** [comment]
> > Thank you @xieaq for your interest!
> > We used explicit code to run SMART in parallel and average the results because parallel computing may cause problems under different OS. I have added the code to the main README page. Please feel free to let me know if you encounter any problems.
> 
> Thanks for your quick reply! Besides that, I'm wondering how to get the marker genes list. Do I need to define them manually?

You may use the marker gene list in data(NSCLC) for human lung, the lists in data(MPOA) and data(visium_mouse_brain) for mouse brain. We will add more marker gene lists in the future but we encourage you to build your own marker gene lists. Additionally, although the marker genes can be shared between cell types, we recommend using more specific marker genes for each cell type.

**Comment by xieaq** [comment]
Thank you very much! :)

**Comment by xieaq** [comment]
Dear Dr. @yyolanda 

I noticed that, in the main README page, it only shows how to get average ```$\theta$```, how about the ```$\beta$``` part?

Thanks for your consideration!

**Comment by yyolanda** [comment]
We did not aim to average the $\beta$ part but it can be averaged in the same manner.
